### ISSUE TITLE
Error in the yarn installation docs

### ISSUE THREAD

**Issue by fidelman** [kettanaito/react-advanced-form-addons#1]
![screen shot 2018-02-21 at 15 56 18](https://user-images.githubusercontent.com/15198653/36486847-d3228618-171f-11e8-844c-374824848c5b.png)
Feel the trick when you install the package using yarn via npm :)

**Comment by kettanaito** [comment]
@fidelman Thanks. Got it fixed under https://github.com/kettanaito/react-advanced-form-addons/commit/3ffbac12f3282072293cd933c46c27b23d1234bc.
