### ISSUE TITLE
fix warning : 'Received `false` for a non-boolean attribute `display`' on ValidationStatus of Input component

### ISSUE THREAD

**Issue by bertrandbuild** [kettanaito/react-advanced-form-addons#2]
Thx for the amazing job 👍

Yet I had issues when trying to use the lib. The basic Input Component works well but display an important warning : `Received 'false' for a non-boolean attribute 'display'`. 

To avoid it I simply replaced `display={ valid || invalid }` on line 128 of Input.jsx by : `display='flex'`
 
I also encountered similar issues with `<Field.Group>` which totally block the render of storybook.

**Comment by kettanaito** [comment]
@Palisanka thanks for contribution!

I will look into that error. This addons library still needs some improvement, as it's somewhat behind the RAF latest version. I'm thinking of merging this one and the main repository together to make testing and maintenance easier.

**Comment by kettanaito** [comment]
@Palisanka I've merged the fix to this issue, alongside with some minor visual updates.

The changes will be release with the patch version of this package today. Once more, thanks for help!

**Update:** This issue is released under `1.3.1` version. Closing.
